<?php

    function dna_menu() {
        $items = array();
        $items['dna'] = array(
            'title' => 'DNA module',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('dna_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['dna-success'] = array(
            'title' => 'DNA Success',
            'page callback' => 'dna_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );

        return $items;
    }

    function dna_form() {
        $form['sequence'] = array(
            '#title' => 'Your half of a DNA helix',
            '#type' => 'textfield',
            '#description' => t('Please enter your DNA sequence'),
            '#element_validate' => array('element_validate_ATGC'),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Sequence',
        );

        return $form;
    }

    function element_validate_ATGC($element) {
        if(preg_match("/[^ACGT]/", $element['#value'])) {
            form_error($element, t('Input can only contain A C G T'));
        }
    }

    function sequence_dna($input) {
        $dna = str_split(str_replace(' ', '', strtoupper($input)));
        $second_helix = array();

        $nucleotides = array(
            'A' => 'T',
            'C' => 'G',
            'T' => 'A',
            'G' => 'C',
        );

        foreach($dna as $nucleotide) {
            if($nucleotides[$nucleotide]) {
                array_push($second_helix, $nucleotides[$nucleotide]);
            }
        }

        return implode('', $second_helix);

    }



    function dna_form_submit($form, &$form_state) {
        $input = str_replace(' ', '', strtoupper($form_state['values']['dna']));
        $dna = str_split($input);

        $nucleotides = array(
            'A' => 'T',
            'C' => 'G',
            'T' => 'A',
            'G' => 'C',
        );

        foreach($dna as $nucleotide) {
            if($nucleotides[$nucleotide]) {
                array_push($second_helix, $nucleotides[$nucleotide]);
            }
        }

        $final_helix = implode('', $second_helix);
        $_SESSION['result'] = $final_helix;
        $_SESSION['input'] = $dna;
        $form_state['redirect'] = 'dna_success';

    }

    function dna_success() {
        $result = $_SESSION['result'];
        $original_input = $_SESSION['input'];
        return "<p>For your input of $original_input, the other half of your helix would be: $result</p>";
    }
